import 'jquery';
import 'bootstrap/dist/js/bootstrap.min.js'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../scss/style.scss'

import './blocks/header'
import './blocks/aside'
import './blocks/content'
import './blocks/loading'
import './blocks/form'
import './blocks/button'

import './modules/data'
import './modules/clustering'
import './modules/norming'
import './modules/targets'
import './modules/mapSetting'
import './modules/mapAnalysis'
import './modules/factorAnalysis'
import './modules/factorSetting'
import './modules/scenarios'
import './modules/taskSetting'
import './modules/taskAnalytic'
import './modules/taskList'
import './modules/information'
import './modules/chatBot'
